from ai_study_buddy.marking.file_question_info.api import (
    assert_unique_detector_question_ids,
    build_detector_question_id_list,
    file_question_info_run_dir_for_pdf,
    get_latest_question_sections_for_file_id,
    get_latest_question_sections_for_pdf_file,
    iter_questions_ordered,
    iter_sections_ordered,
    load_question_sections_json,
    question_page_map_from_question_sections,
    render_file_question_info_pages_for_pdf,
    resolve_question_sections_for_template_file,
    section_hint_strings_for_context,
    validate_question_sections_dict,
)
from ai_study_buddy.marking.file_question_info.post_write import finalize_question_sections_snapshot
from ai_study_buddy.marking.file_question_info.errors import (
    FileQuestionInfoError,
    InvalidGradeOrScopeError,
    MissingGradeOrScopeError,
    QuestionSectionsConsumerError,
    QuestionSectionsDuplicateQuestionIdError,
    QuestionSectionsLookupError,
    QuestionSectionsNotFoundError,
    QuestionSectionsSchemaLoadError,
    QuestionSectionsValidationError,
    UnknownQuestionSectionsSchemaVersionError,
    UnsupportedPdfSubjectError,
)

__all__ = [
    "FileQuestionInfoError",
    "InvalidGradeOrScopeError",
    "MissingGradeOrScopeError",
    "QuestionSectionsConsumerError",
    "QuestionSectionsDuplicateQuestionIdError",
    "QuestionSectionsLookupError",
    "QuestionSectionsNotFoundError",
    "QuestionSectionsSchemaLoadError",
    "QuestionSectionsValidationError",
    "UnknownQuestionSectionsSchemaVersionError",
    "UnsupportedPdfSubjectError",
    "assert_unique_detector_question_ids",
    "build_detector_question_id_list",
    "file_question_info_run_dir_for_pdf",
    "finalize_question_sections_snapshot",
    "get_latest_question_sections_for_file_id",
    "get_latest_question_sections_for_pdf_file",
    "iter_questions_ordered",
    "iter_sections_ordered",
    "load_question_sections_json",
    "question_page_map_from_question_sections",
    "render_file_question_info_pages_for_pdf",
    "resolve_question_sections_for_template_file",
    "section_hint_strings_for_context",
    "validate_question_sections_dict",
]
