steps:
  # Build the container image
  # Build context is chinese_chr_app/ so Dockerfile can access both backend/ and data/
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/chinese-chr-app', '-f', 'chinese_chr_app/chinese_chr_app/backend/Dockerfile', 'chinese_chr_app']
    dir: '.'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/chinese-chr-app']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chinese-chr-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/chinese-chr-app'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'CORS_ORIGINS=https://daydreamedu.org,GCS_BUCKET_NAME=chinese-chr-app-images'
    env:
      - 'CLOUDSDK_RUN_REGION=us-central1'

options:
  logging: CLOUD_LOGGING_ONLY
