"""Shared filesystem utilities for AI Study Buddy."""

__version__ = "0.3.12"

from .leaf_folders import (
    is_goodnotes_excluded_relative_path,
    list_daydreamedu_leaf_folders_under_root,
    list_goodnotes_leaf_folders_under_root,
    list_leaf_folders_under_root,
)
from .main_pdfs import (
    COMPLETION_UNIVERSE_EXCLUDED_DOC_TYPES,
    OnDiskMainPdfRow,
    build_main_pdf_index_for_roots,
    include_in_completion_operator_universe,
    is_inventory_main_pdf,
    is_main_pdf_basename,
    list_main_pdfs_in_leaf_folder,
)
from .on_disk_inventory import (
    FilterCriteria,
    FilterDropdownOptions,
    InventoryMeta,
    WorkflowFilterOptions,
    OnDiskMainPdfCard,
    build_enriched_inventory,
    enrich_on_disk_main_pdf,
    filter_main_pdf_cards,
    sort_main_pdf_cards,
    inventory_meta,
    should_show_is_registered_filter,
    distinct_book_group_names,
    workflow_filter_options,
    filter_dropdown_options,
    filter_meta_for_response,
)
from .path_facets import PathFacets, infer_path_facets
from .pdf_registry_paths import (
    LeafFolderRegistryStatus,
    PdfFileRegistryStatus,
    RegistryPathIndex,
    ScanRootRegistrationBuckets,
    direct_pdf_paths_in_leaf_folder,
    has_template_link,
    is_pdf_registered,
    leaf_folder_registry_status,
    leaf_pdf_file_registry_statuses,
    leaf_registry_statuses_for_included_leaves,
    partition_daydreamedu_leaf_folders,
    partition_goodnotes_leaf_folders,
    pdf_file_registry_status,
    registration_buckets,
    registry_file_for_path,
    registry_file_type_for_path,
    resolved_path_from_registry_row,
    suspicious_all_leaves_marked_non_scan_root,
)
from .roots import resolve_daydreamedu_root, resolve_goodnotes_root

__all__ = [
    "__version__",
    "resolve_daydreamedu_root",
    "resolve_goodnotes_root",
    "list_leaf_folders_under_root",
    "list_daydreamedu_leaf_folders_under_root",
    "list_goodnotes_leaf_folders_under_root",
    "is_goodnotes_excluded_relative_path",
    "PathFacets",
    "infer_path_facets",
    "is_main_pdf_basename",
    "is_inventory_main_pdf",
    "list_main_pdfs_in_leaf_folder",
    "OnDiskMainPdfRow",
    "COMPLETION_UNIVERSE_EXCLUDED_DOC_TYPES",
    "build_main_pdf_index_for_roots",
    "include_in_completion_operator_universe",
    "FilterCriteria",
    "FilterDropdownOptions",
    "WorkflowFilterOptions",
    "OnDiskMainPdfCard",
    "InventoryMeta",
    "enrich_on_disk_main_pdf",
    "filter_main_pdf_cards",
    "sort_main_pdf_cards",
    "build_enriched_inventory",
    "inventory_meta",
    "should_show_is_registered_filter",
    "distinct_book_group_names",
    "workflow_filter_options",
    "filter_dropdown_options",
    "filter_meta_for_response",
    "resolved_path_from_registry_row",
    "RegistryPathIndex",
    "PdfFileRegistryStatus",
    "is_pdf_registered",
    "pdf_file_registry_status",
    "registry_file_for_path",
    "registry_file_type_for_path",
    "has_template_link",
    "direct_pdf_paths_in_leaf_folder",
    "leaf_pdf_file_registry_statuses",
    "LeafFolderRegistryStatus",
    "leaf_folder_registry_status",
    "partition_daydreamedu_leaf_folders",
    "partition_goodnotes_leaf_folders",
    "leaf_registry_statuses_for_included_leaves",
    "ScanRootRegistrationBuckets",
    "registration_buckets",
    "suspicious_all_leaves_marked_non_scan_root",
]
